<?php



function firstturndemo_preprocess(&$variables, $hook)
{
  if($hook == 'block'){

//    xdebug_break();
  }
}


/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */

function firstturndemo_preprocess_node(&$variables)
{
  $node = $variables['node'];
  $date = $node->getCreatedTime();
  $variables['node_title'] = $node->getTitle();
  $variables['node_created_date'] = \Drupal::service('date.formatter')->format($date, 'custom', 'M d, Y');
}


