<?php

/**
 * @file
 * Functions to support theming in the Bartik theme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;


/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function firstturndemo_preprocess_views_view(&$variables) {
  // Remove the "Add new comment" link on teasers or when the comment form is
  // displayed on the page.
  $variables['tester'] = "thing";
}

